# Generated by Django 6.0.1 on 2026-02-23 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPageSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether the public booking page is active')),
                ('page_title', models.CharField(default='Book an Appointment', help_text='Title displayed on the booking page', max_length=255)),
                ('welcome_message', models.TextField(blank=True, help_text='Welcome message shown to customers')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Primary accent color for the booking page', max_length=20)),
                ('logo_url', models.CharField(blank=True, help_text='URL to the logo displayed on the booking page', max_length=500)),
                ('require_phone', models.BooleanField(default=True, help_text='Require customer phone number')),
                ('require_email', models.BooleanField(default=True, help_text='Require customer email address')),
                ('allow_staff_selection', models.BooleanField(default=True, help_text='Allow customers to choose their preferred staff member')),
                ('allow_notes', models.BooleanField(default=True, help_text='Allow customers to add notes to their booking')),
                ('min_advance_hours', models.IntegerField(default=2, help_text='Minimum hours in advance a booking can be made')),
                ('max_advance_days', models.IntegerField(default=30, help_text='Maximum days in advance a booking can be made')),
                ('slot_duration_minutes', models.IntegerField(default=30, help_text='Default time slot duration in minutes')),
                ('buffer_minutes', models.IntegerField(default=0, help_text='Buffer time between appointments in minutes')),
                ('confirmation_message', models.TextField(blank=True, default='Your appointment has been booked successfully. We will confirm it shortly.', help_text='Message shown after a booking is submitted')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation policy text displayed to customers')),
            ],
            options={
                'verbose_name': 'Booking Page Settings',
                'verbose_name_plural': 'Booking Page Settings',
                'db_table': 'online_booking_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('booking_reference', models.CharField(help_text='Auto-generated booking reference (e.g. BK-00001)', max_length=20)),
                ('customer_name', models.CharField(help_text='Customer name as entered in the booking form', max_length=255)),
                ('customer_email', models.EmailField(blank=True, help_text='Customer email', max_length=254)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone number', max_length=50)),
                ('service_id', models.UUIDField(blank=True, help_text='UUID of the booked service', null=True)),
                ('service_name', models.CharField(help_text='Name of the booked service', max_length=255)),
                ('staff_id', models.UUIDField(blank=True, help_text='UUID of the assigned staff member', null=True)),
                ('staff_name', models.CharField(blank=True, help_text='Name of the assigned staff member', max_length=255)),
                ('booking_date', models.DateField(help_text='Date of the appointment')),
                ('booking_time', models.TimeField(help_text='Start time of the appointment')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Duration of the appointment in minutes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or special requests')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the booking was confirmed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('customer', models.ForeignKey(blank=True, help_text='Linked customer record (if found)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_bookings', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Online Booking',
                'verbose_name_plural': 'Online Bookings',
                'db_table': 'online_booking_booking',
                'ordering': ['-booking_date', '-booking_time'],
                'abstract': False,
                'indexes': [models.Index(fields=['hub_id', 'status'], name='online_book_hub_id_af921d_idx'), models.Index(fields=['hub_id', 'booking_date'], name='online_book_hub_id_9de707_idx'), models.Index(fields=['hub_id', 'booking_reference'], name='online_book_hub_id_2abbeb_idx'), models.Index(fields=['hub_id', 'customer_email'], name='online_book_hub_id_31ceb6_idx')],
            },
        ),
    ]
